feat: updated SQL script
stevensblueprint/blueprint_admin_backend pull request #19
Opened 2024-10-30 16:01 UTC by IvanFarfan08

UML Diagram matching the updated SQL script:
<img width="777" alt="image" src="https://github.com/user-attachments/assets/0e97ca1a-5462-4f49-a020-e0eecf968abf">
Sample users, teams and orgs:
<img width="831" alt="image" src="https://github.com/user-attachments/assets/7d7cfed6-bbbe-4030-8f2a-6590ba7289cc">

2024-10-30 16:25 UTC, miguel-merlin requested changes
Pleas keep the naming conventions to `snake_case`. The name of the tables should be plural `Organization`->`organizations`. Do not abbreviate the attributes. If the organization has a name, do not set the attribute to `orgName`, this is redundant. Use bigint for ids, not `INTEGER`

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> -create table blogs  (
Don't delete the blogs

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +    -- Enum type for roles
You have to keep the same conventions in the SQL script. All tables, pk, and fk should be camel case.

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +    CREATE TABLE Organization (
`organizations` not `Organization`

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +        orgId INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
Why orgId? The ORM will complain about this. Use `id`

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +        orgName VARCHAR(255) NOT NULL,
Why are you abbreviating the columns? Also, why are you calling it orgName? If the attribute `name` is in the `organizations` table, it is implicit that the attribute `name` belongs to the `organization`

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +    CREATE TABLE Team (
Same comment here about naming conventions.

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +        teamId INTEGER GENERATED ALWAYS AS IDENTITY,
`id` not `teamId`

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +        orgId INTEGER NOT NULL,
Don't abbreviate please

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +    CREATE TYPE member_role AS ENUM ('E-BOARD', 'TEAM_LEAD', 'PRODUCT_MANAGER', 'DEVELOPER', 'BLUEPRINT_INTERNAL_TEAM');
Change `BLUEPRINT_INTERNAL_TEAM` to `TECH_TEAM`

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +    CREATE TABLE Organization (
Organization is missing:
- Product Manger
- Team Leads

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +    CREATE TABLE Team (
Add a designer field as well

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +        role member_role,
This should be a set of roles. i.e. a member can have multiple roles (e-board, team lead, etc).

2024-10-30 16:25 UTC, miguel-merlin commented on initdb/init.sql
> +    CREATE INDEX idx_member_teamid ON Member(teamId);
What is the purpose of this?

2024-10-30 16:27 UTC, miguel-merlin commented
@IvanFarfan08 Good first iteration, please resolve the comments I made.

2024-11-03 04:58 UTC, IvanFarfan08 commented
<img width="1445" alt="image" src="https://github.com/user-attachments/assets/386802a5-51f3-4ee8-be88-9e11270ee6f6">

2024-11-03 05:16 UTC, miguel-merlin approved these changes

2024-11-03 05:16 UTC, miguel-merlin commented on initdb/init.sql
> +    UPDATE organizations SET team_lead_id = 2, project_manager_id = 2 WHERE id = 1;
**nit**: Add space here for convention

2024-11-03 05:16 UTC, miguel-merlin commented on initdb/init.sql
> +    (2, 'Alice Johnson', 'alicej', 'alicej@stevens.edu', 'a1234', FALSE);
Remove

2024-11-03 05:16 UTC, merged