Eric's changes (🎆 first ever! 🍾)
stevensblueprint/blueprint_admin_backend pull request #6
Opened 2024-04-02 00:57 UTC by ezhang04

Added Attendance Object. Created and Initialized AttendanceRecordRepository database. Created AttendanceController. Added handlers: createAttendance, getAttendanceById, getAttendances, updateAttendance, deleteAttendance.

2024-04-02 01:30 UTC, ezrizhu requested changes
blocking until this is tested on your local environment, per our last conversation

2024-04-03 07:32 UTC, ezhang04 commented
CI is only failing on one testcase. likely a database issue. code is NOT ready for review yet

2024-04-03 07:33 UTC, ezhang04 commented
@miguel-merlin Can I get feedback on the code I have written thus far. just to know if I am on the right track. Thank You

2024-04-03 14:03 UTC, miguel-merlin requested changes
@ezhang04 Looks good! Make sure to change ```AttendanceRecordRepository.java``` to ```repository/attendance/AttendanceRecordRepository.java```. Keep it up!

2024-04-03 14:03 UTC, miguel-merlin commented on src/main/java/com/sitblueprint/admin/service/users/UserServiceImpl.java
> +    public Attendance createAttendance(Attendance attendance){
For this endpoint, you have to check if an Attendance record is already related to a user. If that's the case, return an error since only one attendance record can be related to a user.

2024-04-16 20:28 UTC, miguel-merlin commented
@ezhang04 Please do ```git pull origin main``` on your working branch. There is a new patch that will make the tests succeed.

2024-10-30 16:29 UTC, closed without merging